---
apiVersion: v1
kind: Service
metadata:
  name: stein-api
  labels:
    app: stein
    app-group: api
    component: api
    tier: backend
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    component: api
    app: stein
