apiVersion: v1
kind: Service
metadata:
  name: stein-redis-sentinel
  labels:
    app: stein
    app-group: redis
    component: sentinel
    tier: data
spec:
  clusterIP: None
  ports:
    - port: 26379
      name: redis-sentinel
  selector:
    app: stein
    app-group: redis
    component: sentinel
    tier: data

