apiVersion: v1
kind: Service
metadata:
  name: stein-redis-server
  labels:
    app: stein
    app-group: redis
    component: master
    tier: data
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis-server
  selector:
    app: stein
    app-group: redis
    component: master
    tier: data
