---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: stein-redis-server
  labels:
    app: stein
    app-group: redis
    component: master
    tier: data
spec:
  serviceName: stein-redis-server
  replicas: 3
  template:
    metadata:
      labels:
        app: stein
        app-group: redis
        component: master
        tier: data
      annotations:
        pod.beta.kubernetes.io/init-containers: '[{
            "name": "k8s-redis-ha-server",
            "image": "tarosky/k8s-redis-ha:server-3.0.1",
            "volumeMounts": [{"name": "opt", "mountPath": "/opt"}]
          }]'
    spec:
      containers:
        - name: redis-server
          image: redis:3.2
          command:
            - /opt/cfg/k8s-redis-ha-server
          args:
            - /opt/redis.conf
          env:
            - name: SERVICE
              value: stein-redis-server
            - name: SERVICE_PORT
              value: redis-server
            - name: SENTINEL
              value: stein-redis-sentinel
            - name: SENTINEL_PORT
              value: redis-sentinel
          ports:
            - containerPort: 6379
              name: redis-server
          readinessProbe:
            exec:
              command: ['redis-cli', 'info', 'server']
          volumeMounts:
            - name: redis-server-volume
              mountPath: /data
            - name: opt
              mountPath: /opt
            - name: script
              mountPath: /opt/cfg
              readOnly: false
      volumes:
        - name: redis-server-volume
          emptyDir: {}
        - name: opt
          emptyDir: {}
        - name: script
          configMap:
            name: stein-redis-ha-configmap
            defaultMode: 0755
