version: '3.5'
services:
  stein-api:
    image: glrd/stein-api:latest
    build:
      context: ./
    container_name: stein-api
    command: bash -c 'pm2-runtime start ecosystem.config.js --only stein-api'
    environment:
      - KUE_START_PROCESSING=false
      - KUE_REDIS_PREFIX=q
      - KUE_REDIS_DB=0
      - KUE_REDIS_SENTINEL=true
      - KUE_REDIS_SENTINEL_HOST=stein-redis-sentinel-0.stein-redis-sentinel,stein-redis-sentinel-1.stein-redis-sentinel,stein-redis-sentinel-2.stein-redis-sentinel
      - KUE_REDIS_SENTINEL_PORT=26379,26379,26379
      - KUE_REDIS_SENTINEL_MASTER=mymaster
    links:
      - stein-mysql
      - redis
    ports:
      - "3000:3000"


  stein-queue:
    image: glrd/stein-api:latest
    build:
      context: ./
    container_name: stein-queue
    command: bash -c 'pm2-runtime start ecosystem.config.js --only stein-worker'
    environment:
      - KUE_START_PROCESSING=false
      - KUE_REDIS_PREFIX=q
      - KUE_REDIS_DB=0
      - KUE_REDIS_SENTINEL=true
      - KUE_REDIS_SENTINEL_HOST=stein-redis-sentinel-0.stein-redis-sentinel,stein-redis-sentinel-1.stein-redis-sentinel,stein-redis-sentinel-2.stein-redis-sentinel
      - KUE_REDIS_SENTINEL_PORT=26379,26379,26379
      - KUE_REDIS_SENTINEL_MASTER=mymaster
    links:
      - stein-mysql
      - redis


  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    restart: always

  stein-api-serve:
    image: node:11
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c 'npm i && cp .env.docker .env && npm run start:dev'
    container_name: stein-api-serve
    links:
      - stein-mysql
    ports:
      - "3000:3000"

  stein-mysql:
    image: mysql:5.7
    container_name: stein-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stein
    ports:
      - 3308:3306
