version: '3.5'
services:
  stein-ui:
    image: glrd/stein-ui
    build:
      context: ./
    container_name: stein-ui
    ports:
      - "4200:80"

  stein-ui-serve:
    image: node:11
    volumes:
      - ./:/app
    command: bash -c 'cd /app && npm i && npm rebuild node-sass && npm i -g @angular/cli && ng serve --host 0.0.0.0'
    container_name: stein-ui-serve
    ports:
      - "4200:4200"
